### Numpy

1) Numpy Stands for Numerical Python, which consist of multi-dimensional array objects.

2) We can do mathematical & logical operations on array in Numpy.

3) Operations related to linear algebra,statistics and log can also be done with the help    of numpy.

5) We can do matrix calculations as well in Numpy.

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
np.__version__

'1.22.2'

In [4]:
arr = np.array([10,20,30,40,50])

In [5]:
arr

array([10, 20, 30, 40, 50])

In [6]:
type(arr)

numpy.ndarray

In [7]:
arr1 = np.array([
    [100,200,300,400,500],
    [50,60,70,80,90]
])

In [8]:
arr1

array([[100, 200, 300, 400, 500],
       [ 50,  60,  70,  80,  90]])

In [9]:
arr2 = np.array([
    [10,20,30,40,50],
    [100,200]
])

/tmp/ipykernel_175515/3937742543.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr2 = np.array([


In [10]:
arr2

array([list([10, 20, 30, 40, 50]), list([100, 200])], dtype=object)

In [11]:
arr1

array([[100, 200, 300, 400, 500],
       [ 50,  60,  70,  80,  90]])

In [12]:
arr1.shape

(2, 5)

In [13]:
arr

array([10, 20, 30, 40, 50])

In [14]:
arr.shape

(5,)

In [15]:
arr2 = np.array([
    [10,20,30],
    [40,50,60]
])

In [16]:
arr2

array([[10, 20, 30],
       [40, 50, 60]])

In [17]:
arr2.shape

(2, 3)

In [18]:
arr2.shape = (3,2)

In [19]:
arr2

array([[10, 20],
       [30, 40],
       [50, 60]])

In [20]:
arr2.shape = (6,1)

In [21]:
arr2.shape

(6, 1)

In [22]:
arr2

array([[10],
       [20],
       [30],
       [40],
       [50],
       [60]])

In [23]:
arr4 = np.arange(30)

In [24]:
arr4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [25]:
arr5 = np.arange(10,30)

In [26]:
arr5

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [27]:
arr6 = np.arange(10,25,2)

In [28]:
arr6

array([10, 12, 14, 16, 18, 20, 22, 24])

In [29]:
arr6 = np.arange(0,30).reshape(5,6)

In [30]:
arr6

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [31]:
arr6 = np.zeros(10).reshape(2,5)

In [32]:
arr6

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [33]:
arr7 = np.ones(10).reshape(5,2)

In [34]:
arr7

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

<img src="https://miro.medium.com/max/1330/1*s6gKy2DZ_300dgAeHPgjkQ.png">

In [35]:
arr8 = np.zeros(10,dtype=np.int8).reshape(5,2)

In [36]:
arr8

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int8)

In [37]:
arr8 = np.ones(10).reshape(5,2)*4

In [38]:
arr8

array([[4., 4.],
       [4., 4.],
       [4., 4.],
       [4., 4.],
       [4., 4.]])

In [39]:
arr9 = np.linspace(1,3,100)

In [40]:
arr9

array([1.        , 1.02020202, 1.04040404, 1.06060606, 1.08080808,
       1.1010101 , 1.12121212, 1.14141414, 1.16161616, 1.18181818,
       1.2020202 , 1.22222222, 1.24242424, 1.26262626, 1.28282828,
       1.3030303 , 1.32323232, 1.34343434, 1.36363636, 1.38383838,
       1.4040404 , 1.42424242, 1.44444444, 1.46464646, 1.48484848,
       1.50505051, 1.52525253, 1.54545455, 1.56565657, 1.58585859,
       1.60606061, 1.62626263, 1.64646465, 1.66666667, 1.68686869,
       1.70707071, 1.72727273, 1.74747475, 1.76767677, 1.78787879,
       1.80808081, 1.82828283, 1.84848485, 1.86868687, 1.88888889,
       1.90909091, 1.92929293, 1.94949495, 1.96969697, 1.98989899,
       2.01010101, 2.03030303, 2.05050505, 2.07070707, 2.09090909,
       2.11111111, 2.13131313, 2.15151515, 2.17171717, 2.19191919,
       2.21212121, 2.23232323, 2.25252525, 2.27272727, 2.29292929,
       2.31313131, 2.33333333, 2.35353535, 2.37373737, 2.39393939,
       2.41414141, 2.43434343, 2.45454545, 2.47474747, 2.49494

In [41]:
arr10 = np.logspace(1,10,num=10,base=3)

In [42]:
arr10

array([3.0000e+00, 9.0000e+00, 2.7000e+01, 8.1000e+01, 2.4300e+02,
       7.2900e+02, 2.1870e+03, 6.5610e+03, 1.9683e+04, 5.9049e+04])

## indexing & Slicing technique

In [43]:
arr_1 = np.arange(10,20)

In [44]:
arr_1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [45]:
arr_1[1]

11

In [46]:
arr_1[4]

14

In [47]:
arr_1[-1]

19

In [48]:
arr_1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [49]:
arr_1[3:8]

array([13, 14, 15, 16, 17])

In [50]:
arr6

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [51]:
arr6[0:3:2,0:5:2]

array([[0., 0., 0.]])

In [52]:
arr6[0:6,2:3]

array([[0.],
       [0.]])

In [53]:
arr6[0:3,0:4]

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [54]:
arr6[0:4,3:6]

array([[0., 0.],
       [0., 0.]])

In [55]:
arr10 = np.arange(100,190,10).reshape(3,3)

In [56]:
arr10

array([[100, 110, 120],
       [130, 140, 150],
       [160, 170, 180]])

In [57]:
np.diag(arr10)

array([100, 140, 180])

In [58]:
ar1 = np.array([10,20,30,40])
ar2 = np.array([100,200,300,400])

In [59]:
ar1+ar2

array([110, 220, 330, 440])

In [60]:
ar1 = np.array([10,20,30,40])
ar2 = np.array([100,200,300,400,500,600])

ar1+ar2

ValueError: operands could not be broadcast together with shapes (4,) (6,) 

In [61]:
ar1 = np.array([10,20,30,40])
ar2 = np.array([100,200,300,400])

In [63]:
ar1-ar2

array([ -90, -180, -270, -360])

In [64]:
ar2-ar1

array([ 90, 180, 270, 360])

In [66]:
result = ar1*ar2

In [67]:
result

array([ 1000,  4000,  9000, 16000])

In [68]:
ar1 / ar2

array([0.1, 0.1, 0.1, 0.1])

In [69]:
ar1 % ar2

array([10, 20, 30, 40])

## multidimension array calculations

In [80]:
m1 = np.array([
    [0,0,0],
    [10,10,10],
    [20,20,20],
    [30,30,30]
])

In [81]:
m1

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [82]:
m2 = np.array([1,2,3])

In [83]:
m2

array([1, 2, 3])

In [84]:
m1+m2

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

### logical operations 

In [86]:
mul_d = np.arange(1,21).reshape(5,4)

In [87]:
mul_d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [88]:
mul_d > 5

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [89]:
mul_d[mul_d>5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [90]:
mul_d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [93]:
mul_d[2][2]

11

In [94]:
mul_d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [95]:
mul_d.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [96]:
mul_d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [97]:
arr = np.arange(12).reshape(3,4)

In [98]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [99]:
arr.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

## numpy concatenate

In [100]:
arr1 = np.array([
    [1,2],
    [3,5]
])

In [101]:
arr1

array([[1, 2],
       [3, 5]])

In [102]:
arr2 = np.array([
    [5,6],
    [7,8]
])

In [106]:
arr1


array([[1, 2],
       [3, 5]])

In [103]:
arr2

array([[5, 6],
       [7, 8]])

In [105]:
np.concatenate((arr1,arr2))   #axis 0 , rows wise

array([[1, 2],
       [3, 5],
       [5, 6],
       [7, 8]])

In [108]:
arr1,arr2

(array([[1, 2],
        [3, 5]]),
 array([[5, 6],
        [7, 8]]))

In [109]:
np.concatenate((arr1,arr2),axis=1)   #axis 1 -- column wise

array([[1, 2, 5, 6],
       [3, 5, 7, 8]])

In [110]:
arr1

array([[1, 2],
       [3, 5]])

In [111]:
arr2

array([[5, 6],
       [7, 8]])

In [112]:
np.hstack((arr1,arr2))

array([[1, 2, 5, 6],
       [3, 5, 7, 8]])

In [113]:
np.vstack((arr1,arr2))

array([[1, 2],
       [3, 5],
       [5, 6],
       [7, 8]])

In [114]:
arr1

array([[1, 2],
       [3, 5]])

In [115]:
arr1 = np.arange(1,11)

In [116]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [118]:
arr1.shape = (2,5)

In [119]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

## splitting

In [132]:
arr4 = np.arange(16).reshape(4,4)

In [133]:
arr4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [136]:
np.hsplit(arr4,2)  #

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [123]:
np.vsplit(arr4,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [137]:
arr5 = np.array([[1,2,3],[4,5,6]])

In [138]:
arr5

array([[1, 2, 3],
       [4, 5, 6]])

In [139]:
np.append(arr5,[100,200,300])

array([  1,   2,   3,   4,   5,   6, 100, 200, 300])

In [140]:
arr5

array([[1, 2, 3],
       [4, 5, 6]])

In [141]:
np.append(arr5,[[100,200,300]],axis=0)

array([[  1,   2,   3],
       [  4,   5,   6],
       [100, 200, 300]])

In [142]:
arr5

array([[1, 2, 3],
       [4, 5, 6]])

In [143]:
np.append(arr5,[[13,14],[15,16]],axis=1)

array([[ 1,  2,  3, 13, 14],
       [ 4,  5,  6, 15, 16]])

In [149]:
arr9 = np.array([10,11,12,13,14,15,16,17,18,19])

In [150]:
arr9

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [151]:
np.delete(arr9,2)

array([10, 11, 13, 14, 15, 16, 17, 18, 19])

In [152]:
arr9

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [155]:
arr9 = arr9.reshape(5,2)

In [156]:
arr9

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [157]:
np.delete(arr9,1,axis=0)  #row wise deletion

array([[10, 11],
       [14, 15],
       [16, 17],
       [18, 19]])

In [158]:
arr9

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [159]:
np.delete(arr9,0,axis=1)  #col wise deletion

array([[11],
       [13],
       [15],
       [17],
       [19]])

In [160]:
arr9

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [161]:
arr9[1][1]

13

In [167]:
res = arr9.tolist()

In [168]:
res

[[10, 11], [12, 13], [14, 15], [16, 17], [18, 19]]

In [169]:
arr = np.array([
    [2,4,6],
    [1,3,5],
    [9,7,8]
])

In [170]:
arr

array([[2, 4, 6],
       [1, 3, 5],
       [9, 7, 8]])

In [171]:
def myfunc(x):
    return (x[0] - x[-1])

In [174]:
np.apply_along_axis(myfunc,1,arr)

array([-4, -4,  1])

In [175]:
arr7 = np.array([4,5,6,7,8,9,4,5,6,7])

In [176]:
arr7

array([4, 5, 6, 7, 8, 9, 4, 5, 6, 7])

In [177]:
np.unique(arr7)

array([4, 5, 6, 7, 8, 9])

In [180]:
np.unique(arr7,return_index=True)

(array([4, 5, 6, 7, 8, 9]), array([0, 1, 2, 3, 4, 5]))

## mathematical functions

In [182]:
num = np.array([[0,30,45,60,90],[30,45,90,180,270]])

In [183]:
num

array([[  0,  30,  45,  60,  90],
       [ 30,  45,  90, 180, 270]])

In [184]:
np.sin(num)

array([[ 0.        , -0.98803162,  0.85090352, -0.30481062,  0.89399666],
       [-0.98803162,  0.85090352,  0.89399666, -0.80115264, -0.17604595]])

In [185]:
np.cos(num)

array([[ 1.        ,  0.15425145,  0.52532199, -0.95241298, -0.44807362],
       [ 0.15425145,  0.52532199, -0.44807362, -0.59846007,  0.98438195]])

In [186]:
np.tan(num)

array([[ 0.        , -6.4053312 ,  1.61977519,  0.32004039, -1.99520041],
       [-6.4053312 ,  1.61977519, -1.99520041,  1.33869021, -0.17883906]])

In [187]:
num

array([[  0,  30,  45,  60,  90],
       [ 30,  45,  90, 180, 270]])

In [188]:
arr10 = np.arange(9).reshape(3,3)

In [189]:
arr10

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [190]:
arr11 = np.array([1,2,3])

In [191]:
arr11

array([1, 2, 3])

In [192]:
np.mod(arr10,arr11)

array([[0, 1, 2],
       [0, 0, 2],
       [0, 1, 2]])

In [193]:
np.remainder(arr10,arr11)

array([[0, 1, 2],
       [0, 0, 2],
       [0, 1, 2]])

In [194]:
np.add(arr10,arr11)

array([[ 1,  3,  5],
       [ 4,  6,  8],
       [ 7,  9, 11]])

In [195]:
np.subtract(arr10,arr11)

array([[-1, -1, -1],
       [ 2,  2,  2],
       [ 5,  5,  5]])

In [196]:
np.multiply(arr10,arr11)

array([[ 0,  2,  6],
       [ 3,  8, 15],
       [ 6, 14, 24]])

In [197]:
arr11 = np.array([
    [3,7,5],
    [8,4,3],
    [2,4,9]
])


arr2 = np.array([3,7,5,8,4,3,2,4,9])

In [198]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [199]:
arr2

array([3, 7, 5, 8, 4, 3, 2, 4, 9])

In [200]:
np.min(arr1)

1

In [201]:
np.min(arr2)

2

In [202]:
np.max(arr1)

10

In [203]:
np.max(arr2)

9

In [204]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [210]:
np.min(arr1,axis=0)

array([1, 2, 3, 4, 5])

In [211]:
np.min(arr1,axis=1)

array([1, 6])

In [212]:
np.max(arr1,axis=1)

array([ 5, 10])

In [213]:
np.max(arr1,axis=0)

array([ 6,  7,  8,  9, 10])

In [216]:
np.mean(arr1)

5.5

In [217]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [215]:
np.mean(arr1,axis=0)

array([3.5, 4.5, 5.5, 6.5, 7.5])

In [218]:
np.median(arr1)

5.5

## numpy copy

In [1]:
import numpy as np

In [2]:
arr = np.arange(6)

In [3]:
arr

array([0, 1, 2, 3, 4, 5])

In [4]:
print(id(arr))

140481951105360


In [5]:
arr2 = arr

In [6]:
arr2

array([0, 1, 2, 3, 4, 5])

In [7]:
id(arr2)

140481951105360

In [8]:
id(arr) == id(arr2)

True

In [9]:
arr2.shape = 3,2

In [10]:
arr2

array([[0, 1],
       [2, 3],
       [4, 5]])

In [11]:
arr

array([[0, 1],
       [2, 3],
       [4, 5]])

In [12]:
arr3 = np.arange(10,20)

In [13]:
arr3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [14]:
arr4 = np.copy(arr3)

In [15]:
arr4

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [16]:
arr3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [17]:
id(arr3)

140482945989488

In [18]:
id(arr4)

140481929137008

In [19]:
id(arr3) == id(arr4)

False

In [21]:
arr6 = np.arange(6).reshape(3,2)

In [22]:
arr6

array([[0, 1],
       [2, 3],
       [4, 5]])

In [23]:
id(arr6)

140481931812560

In [24]:
arr7 = arr6.view()

In [25]:
arr7

array([[0, 1],
       [2, 3],
       [4, 5]])

In [26]:
id(arr7)

140481928250832

In [27]:
id(arr6) == id(arr7)

False

In [28]:
arr7.shape = 2,3

In [29]:
arr7

array([[0, 1, 2],
       [3, 4, 5]])

In [30]:
arr6

array([[0, 1],
       [2, 3],
       [4, 5]])

In [31]:
np.char.add(['hello'],['world'])

array(['helloworld'], dtype='<U10')

In [ ]:
np.char.multiply(['demo']*3)